# An example of a services.yaml file in an extension

doctrine:
  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    mappings:
      Contact_Core:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/vendor/celtic34fr/contact-core/src/Entity'
        prefix: 'Bolt\Extension\Celtic34fr\ContactCore'
        alias: ContactCore

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Bolt\Extension\Celtic34fr\ContactCore\AdminMenu:
    class: Bolt\Extension\Celtic34fr\ContactCore\AdminMenu
    arguments: [ '@Symfony\Component\Routing\Generator\UrlGeneratorInterface' ]
    tags: [ 'bolt.extension_backend_menu' ]

  Bolt\Extension\Celtic34fr\ContactCore\Controller\Backend\:
    resource: '%kernel.project_dir%/vendor/celtic34fr/contact-core/src/Controller/Backend/'
    tags: ['controller.service_arguments']
